ALTER TABLE "announcements" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "announcements" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "brands" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "brands" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "configurations" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "configurations" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "ir_attachment" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "ir_attachment" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "product_attributes" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "product_attributes" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "product_categories" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "product_categories" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "product_variants" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "product_variants" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "settings" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "settings" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "shipping_zones" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "shipping_zones" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "tax_rates" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "tax_rates" ADD COLUMN "uid" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "uid" text;